# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

variables:
  - group: PAT for API

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'unitTestReport'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/unitTestReport.xml'
    pathToSources: 'Repairs'
    failIfCoverageEmpty: false