# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug jacocoTestReport -i'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/jacocoTestReport.xml'
    pathToSources: 'Repairs'
    failIfCoverageEmpty: true