# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'testDebugUnitTest'
- task: Gradle@2
  inputs:
    workingDirectory: 'Repairs'
    gradleWrapperFile: 'Repairs/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'createCoverageReport'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: '**/report.xml'
    pathToSources: 'Repairs'
    failIfCoverageEmpty: true
- task: CopyFiles@2
  inputs:
    contents: '**/app-debug.apk'
    targetFolder: '$(build.artifactStagingDirectory)'


- task: PublishBuildArtifacts@1
